matrix:
  include:
    - name: "Python 2.7 on Linux"
      os: linux
      language: python
      python: 2.7
    - name: "Python 3.5 on Linux"
      os: linux
      language: python
      python: 3.5
    - name: "Python 3.6 on Linux"
      os: linux
      language: python
      python: 3.6
    - name: "Python 3.7 on Linux"
      os: linux
      language: python
      python: 3.7
    - name: "Python 3.8 on Linux"
      os: linux
      language: python
      python: 3.8
    - name: "Python nightly on Linux"
      os: linux
      language: python
      python: nightly
    - name: "Python 3.5.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.5.4
        - python --version
        - python -m pip install --upgrade pip virtualenv
        - python -m virtualenv venv
        - source venv/Scripts/activate
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.8
        - python --version
        - python -m pip install --upgrade pip virtualenv
        - python -m virtualenv venv
        - source venv/Scripts/activate
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.6
        - python --version
        - python -m pip install --upgrade pip virtualenv
        - python -m virtualenv venv
        - source venv/Scripts/activate
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.1 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - python --version
        - python -m pip install --upgrade pip virtualenv
        - python -m virtualenv venv
        - source venv/Scripts/activate
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 2.7 on macOS 10.12"
      os: osx
      osx_image: xcode9.3
      language: shell
      before_install:
        - python --version
        - python -m pip install --upgrade pip virtualenv --user
        - python -m virtualenv --python=python venv
        - source venv/bin/activate
    - name: "Python 3.6 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell  # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - python3 -m pip install -U pip virtualenv  --user
        - python3 -m virtualenv --python=python3 venv
        - source venv/bin/activate

before_script:
  - python -m pip install -r requirements.txt
script:
  - python bug890_with_main_guard.py
  - python bug890.py
  - coverage run bug890_with_main_guard.py
  - coverage run bug890.py
